appName = "gomall"

[mysql]
host = "127.0.0.1"
name = "gomall"
password = "root453121"
port = 3306
tablePrefix = ""
user = "root"

[log]
level = "debug"
path = "logs/gomall.log"

[token]
key = "gomall"
expireTime = 3000

[staticPath]
filePath = ""